{% set name = "cuda-nvprune" %}
{% set version = "13.4.49" %}
{% set cuda_version = "13.4" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-ppc64le" %}  # [ppc64le]
{% set platform = "linux-sbsa" %}  # [aarch64]
{% set platform = "windows-x86_64" %}  # [win64]
{% set platform = "windows-arm64" %}  # [win and arm64]
{% set extension = "tar.xz" %}  # [not win]
{% set extension = "zip" %}  # [win]
{% set sha256 = "83c404dcdd859bb51f41da419ef4b0cacec3b2d0d534d27bf25c8cb78dba8617" %}  # [linux64]
{% set sha256 = "f604e755328a1eeee90579ea364058d46edace6ba5685e5159fefce404ca614a" %}  # [aarch64]
{% set sha256 = "046ee2cacaba2de6395f3d18e8bc98d3ef5ba277226dc65617b14355e21d49d6" %}  # [win64]
{% set sha256 = "3fbf17a8f8add7d02c4c5704da7155e0fe72424d42dbc3d088457dd3b1b8f87d" %}  # [win and arm64]

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_nvprune/{{ platform }}/cuda_nvprune-{{ platform }}-{{ version }}-archive.{{ extension }}
  sha256: {{ sha256 }}

build:
  number: 1
  binary_relocation: false
  skip: true  # [osx or ppc64le]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - cf-nvidia-tools 1  # [linux]
  host:
    - cuda-version {{ cuda_version }}
  run:
    - {{ pin_compatible("cuda-version", max_pin="x.x") }}

test:
  requires:
    - patchelf                                                # [linux]
  files:
    - test-rpath.sh                                           # [linux]
  commands:
    - test -f $PREFIX/bin/nvprune  # [unix]
    - if not exist %LIBRARY_BIN%\\nvprune.exe exit 1  # [win]
    - bash test-rpath.sh                                      # [linux]

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: Prunes host object files and libraries to only contain device code
  description: |
    Prunes host object files and libraries to only contain device code for the
    specified targets.
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
