{% set name = "cuda-nvprune" %}
{% set version = "13.1.115" %}
{% set cuda_version = "13.1" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-ppc64le" %}  # [ppc64le]
{% set platform = "linux-sbsa" %}  # [aarch64]
{% set platform = "windows-x86_64" %}  # [win]
{% set extension = "tar.xz" %}  # [not win]
{% set extension = "zip" %}  # [win]

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_nvprune/{{ platform }}/cuda_nvprune-{{ platform }}-{{ version }}-archive.{{ extension }}
  sha256: c7149dec758408511950df3a60a7a3831a589fbc27f268b5c46fc219eca0ab31  # [linux64]
  sha256: a1113c8c70ca66ce10fa15c3794ae4bb3e139a2cffcc5d0223241497b851f70d  # [aarch64]
  sha256: 78c313b1dbee68aa9606626b53922ea312fbefe2fe0fdd2336c46cd4ccd4ebad  # [win]

build:
  number: 0
  binary_relocation: false
  skip: true  # [osx or ppc64le]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - cf-nvidia-tools 1  # [linux]
  host:
    - cuda-version {{ cuda_version }}
  run:
    - {{ pin_compatible("cuda-version", max_pin="x.x") }}

test:
  requires:
    - patchelf                                                # [linux]
  files:
    - test-rpath.sh                                           # [linux]
  commands:
    - test -f $PREFIX/bin/nvprune  # [unix]
    - if not exist %LIBRARY_BIN%\\nvprune.exe exit 1  # [win]
    - bash test-rpath.sh                                      # [linux]

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: Prunes host object files and libraries to only contain device code
  description: |
    Prunes host object files and libraries to only contain device code for the
    specified targets.
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
