{% set name = "cuda-nvprune" %}
{% set version = "13.4.92" %}
{% set cuda_version = "13.4" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-ppc64le" %}  # [ppc64le]
{% set platform = "linux-sbsa" %}  # [aarch64]
{% set platform = "windows-x86_64" %}  # [win64]
{% set platform = "windows-arm64" %}  # [win and arm64]
{% set extension = "tar.xz" %}  # [not win]
{% set extension = "zip" %}  # [win]
{% set sha256 = "c88065ce79484828da2eb89bd6882d74e74c05cdd2868d15e566fa719593a20e" %}  # [linux64]
{% set sha256 = "0b27d76a16f8e8971c9236616e2fa76b455c0eca737079e26954a9dc80c5a23f" %}  # [aarch64]
{% set sha256 = "a3683209925c1da2b6db2a08d0f48699a0a9418e331dddd23f6de99891d46715" %}  # [win64]
{% set sha256 = "4c15d5ecf3a5afa03930a505055c56b399a828880a7c799598101872d5751629" %}  # [win and arm64]

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_nvprune/{{ platform }}/cuda_nvprune-{{ platform }}-{{ version }}-archive.{{ extension }}
  sha256: {{ sha256 }}

build:
  number: 0
  binary_relocation: false
  skip: true  # [osx or ppc64le]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - cf-nvidia-tools 1  # [linux]
  host:
    - cuda-version {{ cuda_version }}
  run:
    - {{ pin_compatible("cuda-version", max_pin="x.x") }}

test:
  requires:
    - patchelf                                                # [linux]
  files:
    - test-rpath.sh                                           # [linux]
  commands:
    - test -f $PREFIX/bin/nvprune  # [unix]
    - if not exist %LIBRARY_BIN%\\nvprune.exe exit 1  # [win]
    - bash test-rpath.sh                                      # [linux]

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: Prunes host object files and libraries to only contain device code
  description: |
    Prunes host object files and libraries to only contain device code for the
    specified targets.
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
